package gov.michigan.dit.timeexpense.util;

import java.util.Date;

public interface IConstants {

	String DEFAULT_DATE_FORMAT = "MM/dd/yyyy";
	String SINGLE_BLANK = " ";
	String ZERO_LENGTH_STRING = "";
	String SYSTEM_EDIT="edit";

	String READY_STATE = "Ready";
	 
	
	/************System Code Error Codes ***********/
	String SYSTEM_CODE_MISSING ="50001";
	String SYSTEM_CODE_ST_DATE_MISSING="50002";
	String SYSTEM_CODE_END_DATE_MISSING="50003";
	String SYSTEM_CODE_DESC_MISSING="50004";
	String SYSTEM_CODE_VALUE_MISSING="50005";


	/** Application cache key values **/
	String APPLICATION_CACHE = "AppCache";
	String STATES = "States";
	String CITIES = "Cities";

	/******* Error Messages ********/
	String INVALID_HRMN_EMPID = "Invalid HRMN Employee Id";
	String MISSING_HRMN_EMPID = "Missing HRMN Employee Id";
	String NO_USER_FOUND = "No DCDS User ID found for the given Employee Id";
	String NO_DCDS_USER_ID="nodcdsuerid";
	String USER_LAST_LOGIN_UPDATE_FAILED = "Failed to update last login date for the user with userId: ";
	String EXPENSE_SUBMIT_ERROR = "Expense Report cannot be submitted with errors";
	

	/** Error Codes **/
	String MULTIPLE_USERS_FOR_EMPLOYEE_ERROR_CODE = "30002";
	String APP_ACCESS_DENIED_ERRCODE = "30003";
	String APP_ACCESS_EXPIRED_ERRCODE = "30004";

	/******* Persistence ********/
	String SECURITY_SCOPE_ALL = "AL";

	/******* Session ********/
	String USER_PROFILE_SESSION_KEY_NAME = "User";
	String USER_SUBJECT_SESSION_KEY_NAME = "UserSubject";
	String LEFT_NAV_OPTIONS = "LeftNavOptions";
	String FIRST_TIME = "firstTime";
	String LAST_OPERATION = "LastSuccessfulOperation";

	String LOGGED_IN_USER_DEPARTMENT = "dept";
	String LOGGED_IN_USER_AGENCY = "agy";
	String LOGGED_IN_USER_TKU = "tku";
	String TKUOPT_TA_OPTIONS = "tkuOptTaOptions";
	String EMP_HEADER_INFO = "empHeaderInfo";
	String EXPENSE_DETAILS_LIST = "EXPENSE_DETAILS_LIST";
	String EXPENSE_DETAILS_LIST_WITH_APPLIED_CB = "ExpenseDetailsListWithAppliedCB";
	String EXPENSE_SESSION_DATA = "ExpenseSessionData";
	String CURR_EXPENSEMASTER = EXPENSE_SESSION_DATA;
	String CURR_EXPENSEMASTER_FROM_TREQ = "ExpenseSessionDataFromTreq";
	String EXPENSE_DETAIL_DELETED_CB_ROWS = "DeleteExpenseCodingBlocksList";
	String LEFT_NAV_CURRENT_MODULE_ID = "leftNavCurrentModuleId";
	String LEFT_SYS_CODE_MODULE_ID="leftSystCodeModuleId";
	String LOGGED_IN_USER_APPOINTMENT_ID = "apptId";
	String ADVANCE_CURRENT_ADVANCE_EVENT = "currentAdvanceEvent";
	String ADVANCE_CURRENT_ADVANCE_MASTER = "currentAdvanceMaster";
	String ADVANCE_CURRENT_ADVANCE_MASTER_INDEX = "currentAdvanceMasterIndex";
	String EXPENSE_CURRENT_EXPENSE_MASTER_INDEX = "currentExpenseMasterIndex";
	String EXPENSE_CURRENT_EXPENSE_EVENT = "currentExpenseEvent";
	String EXPENSE_REIMBURSEMENT_APPROVAL_CATEGORY = "C";
	String EXPENSE_TOTAL_OUTSTANDING_ADVANCE_AMOUNT = "totalOutstandingAdvanceAmount";
	String MODIFY_BUTTON_STATE_SESSION = "modifyClicked";
	String EXPENSE_TRANSACTION_LISTING_BY_APPOINTMENT = "expenseTransListingAppointment";
	String ADVANCE_OUTSTANDING_LIST = "AdvanceOutStandingList";
	String EXPENSE_SUMARY_SESSION_DATA = "ExpenseSummaryObjList";
	String EXPENSE_LIQUIDATION_LIST_IN_SESSION = "liquidationList";
	String MULTIPLE_APPTS_FOR_EXPENSE = "MULTIPLE_APPTS_FOR_EXPENSE";
	String APPT_SEARCH_DATE = "apptSearchDate";

	String USER_CONTEXT = "UserContext";
	String EXP_SUMMARY_REPORT_DATA = "ExpSummaryReportData";

	/** Select employee session variables */
	String SE_USER_SELECTED_DEPT = "SE_UserSelectedDepartment";
	String SE_USER_SELECTED_SYS_CODE = "SE_UserSelectedSystemCode";
	String SE_USER_SELECTED_AGENCY = "SE_UserSelectedAgency";
	String SE_USER_SELECTED_TKU = "SE_UserSelectedTku";
	String SE_EMP_ID = "SE_EmpId";
	String SE_LAST_NAME = "SE_Lastname";
	String SE_APPT_SEARCH_DATE = "SE_ApptSearchDate";
	
	String TRAVEL_REQUISITION_SESSION_DATA = "TravelRequisitionSessionData";

	/*********************/
	String USER_SUBJECT_FOR_CB_STORE = "USER_SUBJECT_FOR_CB_STORE";
	String CODING_BLOCK_OPTIONS = "CODING_BLOCK_OPTIONS";
	String CODING_BLOCK_STORE = "CODING_BLOCK_STORE";
	String ADVANCE_MAX_REVISION_NUMBER = "advanceMaxRevisionNumber";
	int CB_INDEX_LENGTH = 5;
	int CB_PCA_LENGTH = 5;
	int CB_GRANT_NUMBER_LENGTH = 6;
	int CB_GRANT_PHASE_LENGTH = 2;
	int CB_PROJECT_NUMBER_LENGTH = 6;
	int CB_PROJECT_PHASE_LENGTH = 2;
	int CB_AGENCY_CODE_1_LENGTH = 4;
	int CB_AGENCY_CODE_2_LENGTH = 4;
	int CB_AGENCY_CODE_3_LENGTH = 6;
	int CB_MULTI_LENGTH = 10;

	/******* Action Responses *******/
	String SUCCESS = "success";
	String FAILURE = "failure";
	String NO_USER="nouser";//bug 335
	String SECURITY_FAILURE = "securityFailure";
	String GLOBAL_EXCEPTION = "g_exception";

	/******* Expense Error Codes ************/

	String EXPENSE_DATE_EARLIER_THAN_TIMEEXPENSE_APPLICATION_START_DATE = "36001";
	String EXPENSE_TO_DATE_EARLIER_THAN_EXPENSE_FROM_DATE = "36002";
	String EXPENSE_DATES_SPAN_FISCAL_YEAR = "36003";
	String EXPENSE_FROM_DATE_AFTER_SYSTEM_PERMISSION = "50012";
	String ADVANCE_REQUEST_END_DATE = "50013";
	String TREQ_FROM_DATE_AFTER_SYSTEM_PERMISSION_CLIENT_MESSAGE = "50014";
	String ADVANCE_SUBMIT_APPROVE_END_DATE = "50015";
	String ADVANCE_SAVE_END_DATE = "50016";
	String EXPENSE_FROM_DATE_AFTER_SYSTEM_PERMISSION_CLIENT_MESSAGE = "50017";	
	String INVALID_APPOINTMENTS_FOR_EXPENSE_DATES = "36004";
	String MULTIPLE_FACS_AGENCY_FOR_EXPENSE_DATES = "36005";
	String AUTHORIZATION_CODES_EMPTY = "36006";
	String EXPENSE_DETAILS_DATE_NOT_BETWEEN_EXPENSE_ID_DATE = "36007";
	String EXPENSE_DETAILS_DEPARTURE_TIME_EARLIER_THAN_RETURN_TIME = "36008";
	String EXPENSE_DETAILS_DEPART_TIME_RETURN_TIME_COMBINATION_NOT_EXISTS = "36009";
	String EXPENSE_DETAILS_MILES_REQUIRED_FOR_MILEAGE_EXPENSE_TYPE = "36010";
	String EXPENSE_DETAILS_REIMBURSEMENT_AMOUNT_CHANGED = "36036";
	String EXPENSE_DETAILS_COMMENTS_REQUIRED_WHEN_REIMBURSEMENT_AMOUNT_CHANGED = "36011";
	String EXPENSE_DETAILS_COMMENTS_REQUIRED_FOR_EXPENSE_TYPE = "36012";
	String EXPENSE_PROFILE_RULE_PRE_AUDIT_REQUIRED = "1001";
	String EXPENSE_DETAILS_WARNING_FROM_TO_STATE_FOR_IN_STATE_TRAVEL = "36028";
	String EXPENSE_LIQUIDATIONS_ERROR_LIQUIDATED_AMOUNT_GREATER_THAN_OUTSTANDING_ADVANCE = "36029";
	String EXPENSE_LIQUIDATIONS_ERROR_LIQUIDATED_AMOUNT_CANNOT_BE_REDUCED = "36030";
	String EXPENSE_TODATE_GREATER_THAN_CURRENT_PP_ENDDATE = "36033";
	String AMT_LIQUIDATED_GREATER_THAN_INDIVIDUAL_ADVANCE = "36034";
	String ADVANCE_LIQUIDATION_NOT_CURRENT = "36042";
	String EXP_DTL_AMT_ZERO_ERROR = "36035";
	String INVALID_EXPENSE_TYPE = "36039";
	String EXPENSE_DETAILS_VICINITY_MILES_ENTERED = "36040";
	String EXPENSE_DETAILS_COMMENTS_REQUIRED_VICNITY_MILES_ENTERED = "36041";
	String EXPENSE_DETAILS_LOCATION_NOT_SELECT_CITY = "36043";
	String EXPENSE_DETAILS_VALIDATE_MEAL_TIMES = "36049";
	String EXPENSE_DETAILS_VALIDATE_EXPENSE_BARGAINING_UNIT = "36050";
	String EXPENSE_DETAILS_VALIDATE_PREMIUM_MILEAGE = "36051";
	String EXP_DEPARTURE_RETURN_TIME_MISSING_WARNING = "40012";
	String EXP_DETAIL_COMMENT_MISSING_FOR_INTERNATIONAL_EXPENSE = "36037";
	String EXPENSE_COMPARE_WITH_TIME_SHEET_HOURS = "36047";
	String EXPENSE_TIME_SHEET_EXISTANCE="36048";
	String CODING_BLOCK_REQUIRED_FOR_PDF_EXPENSES = "36055";
	String USER_CREATE_ONLY_PDF_EXPENSES = "50010";
	String OVERNIGHT_NOT_SELECTED_FOR_LODGING_EXPENSE_TYPE = "36056";
	String EXPENSE_DATES_EXIST="36057";//CN-BUG-208
	
	 /************* Common Mileage Error Codes ************/
	String COMMON_MILEAGE_DELETE_LOCATION="50006";
	String COMMON_MILEAGE_AGY_DEPT="50007";
	
	/******* Travel Requisition Error Codes ************/
	String TRAVEL_REQUISITION_AMT_ZERO_ERROR = "36054";

	
	
	/******* Advance Error Codes ************/
	String ADVANCE_STARTING_ERROR_MESSAGE = "40000";
	String ADVANCE_ENDING_ERROR_MESSAGE = "40100";
	String ADVANCE_DATE_EARLIER_THAN_TIMEEXPENSE_APPLICATION_START_DATE = "40000";
	String ADVANCE_TO_DATE_EARLIER_THAN_EXPENSE_FROM_DATE = "40001";
	String ADVANCE_DATES_SPAN_FISCAL_YEAR = "40002";
	String ADVANCE_MUTIPLE_APPOINTMENTS_FOR_DATE_RANGE = "40003";
	String ADVANCE_INVALID_APPOINTMENTS_FOR_DATE_RANGE = "40004";
	String ADVANCE_MANUAL_WARRANT_DOCUMENT_NUMBER_MISSING = "40005";
	String ADVANCE_MANUAL_DEPOSIT_DOCUMENT_NUMBER_MISSING = "40006";
	String ADVANCE_MANUAL_AMOUNT_MISSING = "40007";
	String ADVANCE_REQUESTDATE_GREATER_THAN_CURRENT_PP_ENDDATE = "40011";
	/************* Expense Constants ************/

	String NOTIFICATION_NOT_SENT_SINCE_USERID_NOT_DEFINED = "10551";
	String NOTIFICATION_NOT_DUE_TO_SYSTEM_PROBLEMS = "10550";

	String NEW = "NEW";
	String MILEAGE_TYPE = "Miles";
	String EXPENSE_RULE_TYPE = "EXPENSE_TYPE_RULES";
	String EXPENSE_ID_TAB = "ID";
	String EXPENSE_DETAILS_TAB = "Expenses";
	String EXPENSE_CODING_BLOCK_TAB = "Coding Block";
	String EXPENSE_SUMMARY_TAB = "Summary";

	String FACS_AGENCY = "facs_agency";
	String EXP_ERR_SRC_ID_TAB = "ID";
	String EXP_ERR_SRC_DTL_TAB = "Exp Line";
	String EXP_ERR_SRC_CB_TAB = "CB-Line";
	String EXP_ERR_SRC_LIQ_TAB = "Liq";
	String EXP_ERR_SRC_CB_TAB_PREFIX = "CB";

	String INVALID_FACS_AGENCY_FOR_EXPENSE_DATES = "36038";
	String EXPENSE_DETAILS_DEPARTURE_TIME_MUST_EXIST = "36027";

	Integer MILEAGE_RELATED_RULE_ID = 1006;
	Integer TAXABLE_EXPENSES = 1009;
	Integer EXPENSE_TYPE_RULE_COMMENTS_REQUIRED = 1007;

	String TRANSACTION_LIST_ADJUSTED_ONLY = "TRAN_ADJ";
	String TRANSACTION_LIST_NON_ADJUSTED_ONLY = "TRAN_WO_ADJ";
	String TRANSACTION_LIST_BOTH_ADJUSTED_AND_NON_ADJUSTED = "TRAN";

	String EXPENSE_HISTORY_LIST_VERSION_HEADER = "Version";
	String EXPENSE_HISTORY_LIST_MODIFIED_USER_ID_HEADER = "Action Taken By";
	String EXPENSE_HISTORY_LIST_COMMENTS_HEADER = "Comments";
	String EXPENSE_HISTORY_LIST_MODIFIED_DATE_HEADER = "Action Date";
	String EXPENSE_HISTORY_LIST_ACTION_CODE_HEADER = "Action Code";
	String EXPENSE_DETAILS_LIST_TO_BE_UPDATED = "EXPENSE_DETAILS_LIST_TO_BE_UPDATED";

	/************** Advance Constants *****************/

	String ALL_ADV_AWAITING_APPR = "ADV";
	String ADJ_ADV_AWAITING_APPR = "ADV_ADJ";
	String NON_ADJ_ADV_AWAITING_APPR = "ADV_NON_ADJ";
	String ADVANCE_TRANSACTION_LISTING = "advanceTransListing";
	String ADVANCE_ERROR_SOURCE = "Advance";
	String TRAVEL_REQUISITION_ERROR_SOURCE = "Travel Requisition";
	

	/************** Approval Constants *****************/
	String APPROVAL_LIST_EXPENSES_ONLY = "APPR_EXP";
	String APPROVAL_LIST_ADVANCES_ONLY = "APPR_ADV";
	String APPROVAL_LIST_ADJUSTMENTS_ONLY = "APPR_ADJ";
	String APPROVAL_LIST_ADVANACES_EXPENSES = "APPR_ALL";

	/************* System Codes ***********/

	String TIME_EXPENSE_START_DATE_SYSTEM_CODE = "TE01";
	String NEWS_BULLETIN_ITEMS = "WB%";
	String ADVANCE_PAYROLL_SYSTEM_CODE = "PT03";
	String ADVANCE_MANUAL_WARRANT_SYSTEM_CODE = "PT04";
	
	//Check if the expense FROM date exceeds the System permissible limit
	String EXPENSE_END_DATE_SYSTEM_CODE = "TE02";
	String ADVANCE_REQUEST_END_DATE_SYSTEM_CODE = "TE03";
	String TRAVEL_REQ_END_DATE_SYSTEM_CODE = "TE04";
	String ADVANCE_END_DATE_SYSTEM_CODE = "TE05";
	String ADVANCE_SUBMIT_APPROVE_END_DATE_SYSTEM_CODE = "TE06";
  
	/************* Security Modules ***********/

	String APP_MODULE_ID = "TEXW001";
	String EXPENSE_EMPLOYEE = "EXPW001";
	String EXPENSE_MANAGER = "EXPW002";
	String EXPENSE_STATEWIDE = "EXPW003";
	String ADVANCE_EMPLOYEE = "ADVW001";
	String ADVANCE_MANAGER = "ADVW002";
	String ADVANCE_STATEWIDE = "ADVW003";
	String ADVANCE_ADJUSTMENT_MODULE = "ADVF001";
	String APPROVE_WEB_MANAGER = "APRW003";
	String APPROVE_WEB_STATEWIDE = "APRW004";
	String APPROVE_WEB_TRAVEL_COORDINATOR = "APRF007";
	String APPROVE_WEB_REGIONAL = "APRF008";
	String APPROVE_CENTRAL_HR = "APRF009";
	String APPROVE_CENTRAL_FINANCE_PRIMARY = "APRF010";
	String APPROVE_CENTRAL_FINANCE_SECONDARY = "APRF011";
	String APPROVE_CENTRAL_OFM = "APRF012";
	String EMPLOYEE_REPORT_RECEIPTS_REQUIRED = "EXPR001";
	String EMPLOYEE_REPORT_EXCEPTION = "EXPR002";
	String EMPLOYEE_REPORT_ROUTINE_TRAVELER = "EXPR003";
	String EMPLOYEE_REPORT_TRANSACTION_LEDGER = "EXPR004";
	String MANAGER_REPORT_RECEIPTS_REQUIRED = "EXPR005";
	String MANAGER_REPORT_EXCEPTION = "EXPR006";
	String MANAGER_REPORT_ROUTINE_TRAVELER = "EXPR007";
	String MANAGER_REPORT_TRANSACTION_LEDGER = "EXPR008";
	String MANAGER_REPORT_NON_ROUTINE_TRAVELER = "EXPR013";//AI-25977
	String STATEWIDE_REPORT_RECEIPTS_REQUIRED = "EXPR009";
	String STATEWIDE_REPORT_EXCEPTION = "EXPR010";
	String STATEWIDE_REPORT_ROUTINE_TRAVELER = "EXPR011";
	String STATEWIDE_REPORT_TRANSACTION_LEDGER = "EXPR012";
	String STATEWIDE_REPORT_NON_ROUTINE_TRAVELER = "EXPR014";//AI-25977
	String AUDIT_COMPLETE_AUTHORIZATION_CODE = "EXPF002";
	String EXPENSE_ADJUSTMENT_MODULE = "EXPF001";
	String STATEWIDE_PARAM_SYSTEM_CODES = "PRMW079";
	String TRAVEL_REQUISITIONS_EMPLOYEE = "NTRW001";
	String TRAVEL_REQUISITIONS_MANAGER = "NTRW002";
	String NON_ROUTINE_TRAVEL_REQUISITION="NTRW002";
	String TRAVEL_REQUISITIONS_STATEWIDE = "NTRW003";
	String STATEWIDE_AGENCY_OPTION_LOCATION = "AGYW001";
	String STATEWIDE_AGENCY_LOC_AVAILABLE="EXPF004";
	
    String SUPER_USER = "SECW999";
	String PDF_MODULE = "EXPF003";
	String APPROVE_PDF_MODULE = "APRF014";
	/************* String Constants ***********/

	String STRING_NONE = "none";
	String STRING_BLANK = "";
	String STRING_WARNING = "W";
	String STRING_ERROR = "E";
	String STRING_INLINE = "inline";
	String STRING_PDF_CATEGORY_CODE = "P";

	/************* Time & Expense Actions ***********/

	String SUBMIT = "SUBM";
	String PROCESSED = "PROC";
	String REJECTED = "RJCT";
	String EXTRACTED = "XTCT";
	String APPROVED = "APPR";
	String HOURS_ADJUSTMENT_SENT = "HSNT";
	String AUDIT = "AUDT";
	String SPLIT = "SPLT";
	String CERTIFY = "ECRT";

	/******* Coding Block Constants *************/

	// String F_CB_VALIDATE_OBJECT = "f_cb_validate";
	String CODING_BLOCK_VALID_CODE = "10200";
	String INDEX_ELEMENT_TYPE = "IDX";
	String PCA_ELEMENT_TYPE = "PCA";
	String GRA_ELEMENT_TYPE = "GRA";
	String PRO_ELEMENT_TYPE = "PRO";
	String AG1_ELEMENT_TYPE = "AG1";
	String AG2_ELEMENT_TYPE = "AG2";
	String AG3_ELEMENT_TYPE = "AG3";
	String MUL_ELEMENT_TYPE = "MUL";
	String CODING_BLOCK_PERCENT_NOT_EQUAL_100 = "36024";
	String CODING_BLOCK_IDENTICAL = "36026";
	String CODING_BLOCK_ERROR = "CODING_BLOCK_ERROR";
	String CODING_BLOCK_ELEMENTS_DATA = "CodingBlockElement";
	String CODING_BLOCK_LIST_TO_BE_SAVED = "CODING_BLOCK_LIST_TO_BE_SAVED";
	String CODING_BLOCK_LIST = "CODING_BLOCK_LIST";
	String CODING_BLOCK_SPECIFIC_CB_REQUIRED = "36052";
	String CODING_BLOCK_MIN_INDEX_PCA_ERROR_CODE = "10149";
	String CODING_BLOCK_MAX_INDEX_PCA_ERROR_CODE = "10158";

	/************ Expense Profile Rules *************/
	int EXPENSE_PROFILE_RULE_ADVANCES_ALLOWED = 1000;
	String EXPENE_PROFILE_AGENCY_DEFAULT = "Agy Dfault";
	
	/************** Security Constants *****************/
	int SECURITY_NO_MODULE_ACCESS = 0;
	int SECURITY_INQUIRY_MODULE_ACCESS = 1;
	int SECURITY_UPDATE_MODULE_ACCESS = 2;
	
	
    /*************** Notification Messages ***********************/
	String NOTIFICATION_ADVANCE_REQUEST_SUBMIT_BY_SUBJECT = "060";
	String NOTIFICATION_ADVANCE_REQUEST_SUBMIT_BY_OTHER = "061";
	String NOTIFICATION_ADVANCE_REQUEST_MODIFIED_BY_SUBJECT = "062";
	String NOTIFICATION_ADVANCE_REQUEST_MODIFIED_BY_OTHER = "063";
	String NOTIFICATION_ADVANCE_REQUEST_ADJUSTED_BY_SUBJECT = "064";
	String NOTIFICATION_ADVANCE_REQUEST_ADJUSTED_BY_OTHER = "065";
	String NOTIFICATION_ADVANCE_REQUEST_APPROVED = "066";
	String NOTIFICATION_ADVANCE_REQUEST_REJECTED = "067";
	String NOTIFICATION_ADVANCE_REQUEST_ADJUSTMENT_APPROVED = "068";
	String NOTIFICATION_ADVANCE_REQUEST_ADJUSTMENT_REJECTED = "069";
	
	/*************** Notification Messages ***********************/
	String NOTIFICATION_TRAVEL_REQ_SUBMIT_BY_SUBJECT = "080";
	String NOTIFICATION_TRAVEL_REQ_REQUEST_SUBMIT_BY_OTHER = "081";
	String NOTIFICATION_TRAVEL_REQ_REQUEST_MODIFIED_BY_SUBJECT = "082";
	String NOTIFICATION_TRAVEL_REQ_REQUEST_MODIFIED_BY_OTHER = "083";
	String NOTIFICATION_TRAVEL_REQ_REQUEST_APPROVED = "084";
	String NOTIFICATION_TRAVEL_REQ_REQUEST_REJECTED = "085";
	//CN BUG-147
	String NOTIFICATION_TRAVEL_REQ_NEXT_ACTION_CODE = "096";
	/***************Notification TREQ Person ****************************/
	String NOTIFICATION_TRAVEL_REQ_DIRECTOR_EMAIL = "TREQ Director";
    //CN-BUG 147 
	/*************** Expense Notification Messages ***********************/
	String NOTIFICATION_EXPENSE_REQUEST_SUBMIT_BY_SUBJECT = "050";
	String NOTIFICATION_EXPENSE_REQUEST_SUBMIT_BY_OTHER = "051";
	String NOTIFICATION_EXPENSE_REQUEST_MODIFIED_BY_SUBJECT = "052";
	String NOTIFICATION_EXPENSE_REQUEST_MODIFIED_BY_OTHER = "053";
	String NOTIFICATION_EXPENSE_REQUEST_ADJUSTED_BY_SUBJECT = "054";
	String NOTIFICATION_EXPENSE_REQUEST_ADJUSTED_BY_OTHER = "055";
	String NOTIFICATION_EXPENSE_REQUEST_APPROVED = "056";
	String NOTIFICATION_EXPENSE_REQUEST_REJECTED = "057";
	String NOTIFICATION_EXPENSE_REQUEST_ADJUSTMENT_APPROVED = "058";
	String NOTIFICATION_EXPENSE_REQUEST_ADJUSTMENT_REJECTED = "059";
		
	/*************** PDF Notification Messages ***********************/
	String NOTIFICATION_PDF_REQUEST_SUBMIT_BY_SUBJECT = "086";	
	String NOTIFICATION_PDF_REQUEST_SUBMIT_BY_OTHER = "088";
	String NOTIFICATION_PDF_REQUEST_MODIFIED_BY_SUBJECT = "089";
	String NOTIFICATION_PDF_REQUEST_MODIFIED_BY_OTHER = "090";
	String NOTIFICATION_PDF_REQUEST_ADJUSTED_BY_SUBJECT = "091";
	String NOTIFICATION_PDF_REQUEST_ADJUSTED_BY_OTHER = "092";	
	String NOTIFICATION_PDF_REQUEST_APPROVED = "087";
	String NOTIFICATION_PDF_REQUEST_REJECTED = "093";
	String NOTIFICATION_PDF_REQUEST_ADJUSTMENT_APPROVED = "094";
	String NOTIFICATION_PDF_REQUEST_ADJUSTMENT_REJECTED = "095";
	
	/***************Notification Person****************************/
	String NOTIFICATION_PDF_APPROVE = "PDF Approve";	
     
	/*************** Report Constants **********************/

	Date defaultStartDate = new Date("01/01/1900");
	Date defaultEndDate = new Date("12/31/2222");
	String EXCEL_EXPORT = "Excel";
	

	/*************** Status Messages for History Tab **********************/
	String APPROVAL_STEP1 = "APRW";
	String APPROVAL_STEP2 = "ATCW";
	String APPROVAL_STEP3 = "ARGW";
	String APPROVAL_STEP4 = "APPW";
	String APPROVAL_STEP5 = "AFFW";
	String APPROVAL_STEP6 = "AF2W";
	String APPROVAL_STEP7 = "AOFW";
	String APPROVAL_AUTO = "ASYS";
	String APPROVAL_STEP8 = "ASYS";

	String HISTORYMSG_SUBMIT = "Awaiting Approvals";
	String HISTORYMSG_PROCESSED = "Processed";
	String HISTORYMSG_REJECTED = "Rejected";
	String HISTORYMSG_APPROVED_EXTRACTED_HOURS_ADJUSTMENT_SENT = "Approvals Complete";
	String HISTORYMSG_APPROVALSTEPS = "Additional Approvals Required";
	
	String HISTORYMSG_NEEDSTOBESUBMITTED = "Needs to be submitted";

	/*************** For HELP URL Session Values **********************/
	String URLCNT = "URLCNT";
	String URLTRNG = "URLTRNG";
	String URLFAQ = "URLFAQ";

	// Crystal Reports Parameters
	String CrystalReportsParms = "CrystalReportsParms";
	String CrystalReportsAlias = "CrystalReportsAlias";
	String CrystalSchema = "HRDCD.";
	
	/************************MEALS CATEGORY******************************/
	String MEALS_CATEGORY = "BLD";
	
	/********Expense Locations*******************/
	
	String EXPENSE_LOCATION_DEFAULT_ORDER = "1";
	String LOCATION_ERROR_CITY_IN_STATEWIDE = "50008";
	String LOCATION_ERROR_CITY_IN_AGENCY = "50009";
	
}
